#!/usr/bin/env bash
# Configure Nginx server so that '/redirect_me' is redirecting to another page.
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo nginx -s reload
