#!/usr/bin/env bash
# Script to display Besst school 10 times with while loop and if statement
counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ "$counter" = 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
